markdown: "kramdown"
paginate: 7
highlighter: "pygments"
safe: false
environment: "dev"
artifact_commit: "dev"
asset_prefix: "/asset"
static_prefix: "/static/dev"
gems:
  - "jekyll-paginate"
  - "jekyll-sitemap"
  - "pygments.rb"
exclude:
  - "LICENSE"
  - "README.md"
  - "bosh"
  - "ci"
  - "Gemfile"
  - "vendor"
