languageCode = "en-us"
title = "Danny Berger"
copyright = "Unless noted, software code is licensed under MIT License and all other content under CC-BY."
disqusShortname = "dpb587"
googleAnalytics = "UA-37464314-1"
theme = "current"
enableRobotsTXT = true
enableGitInfo = true
buildFuture = true
pygmentsCodefences = true
pygmentsUseClasses = "true"
paginate = "30"

[build]
writeStats = true

[author]
  name = "Danny Berger"
  email = "dpb587@gmail.com"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/post/:year/:month/:day/:slug/"
  page = "/:filename/"
  photo = "/:sections/:filename/"
  tweet = "/tweet/:filename/"

[[menu.main]]
  name = "hello"
  url = "/"
  weight = 1

[[menu.main]]
  name = "thoughts"
  url = "/post/"
  weight = 2

[[menu.main]]
  name = "projects"
  url = "/project/"
  weight = 3

[[menu.main]]
  name = "photos"
  url = "/photo/"
  weight = 4

# [[menu.main]]
#  name = "tweets"
#  url = "/tweet/"
#  weight = 5

[[menu.main]]
  name = "talks"
  url = "/prezo/"
  weight = 6

[[menu.main]]
  name = "résumé"
  url = "/about/"
  weight = 7

[[menu.social]]
  name = "GitHub"
  url = "https://github.com/dpb587"
  weight = 1
  colorClass = "black"

[[menu.social]]
  name = "Twitter"
  url = "https://twitter.com/dpb587"
  weight = 2
  colorClass = "blue-400"

[[menu.social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/dpb587/"
  weight = 3
  colorClass = "blue-700"

[params]
  description = ""
  assetUrl = "https://dpb587-website-us-east-1.s3.amazonaws.com/asset/gallery/"
  imgproUrl = "http://localhost:8088/d0c48e72-6c4f-4c24-ba62-7ebefd4a51da"
  enableComments = false
  github_repo = "https://github.com/dpb587/dpb587.me"
